module.exports = function(app) {
    var HotelController = {
        init: function(DB){
            DB.find({}, function(err, hoteis) {
                if (hoteis.length === 0) {
                    DB.create({cod:1, localidade:"Araruama", nome:"Mercatto Casa Hotel"});
                    DB.create({cod:2, localidade:"Macae", nome:"Boulevard Higienopolis Residence Hotel"});
                    DB.create({cod:3, localidade:"Campos", nome:"Lucca Hotel Pousada"});
                    DB.create({cod:4, localidade:"Resende", nome:"Kananxue Hotel"});
                    DB.create({cod:5, localidade:"Araruama", nome:"Villa Verde Pousada"});
                    DB.create({cod:6, localidade:"Marica", nome:"Pousada Sao Silmares"});
                    DB.create({cod:7, localidade:"Saquarema", nome:"Hotel George Sand"});
                    DB.create({cod:8, localidade:"Campos", nome:"Pousada Vesuvio"});
                    DB.create({cod:9, localidade:"Duque De Caxias", nome:"Aragipe Praia Hotel"});
                    DB.create({cod:10, localidade:"Penedo", nome:"Capitao Nareia Pousada"});
                    DB.create({cod:11, localidade:"Penedo", nome:"Hotel Bellevue"});
                    DB.create({cod:12, localidade:"Itatiaia", nome:"155 Hotel"});
                    DB.create({cod:13, localidade:"Angra Dos Reis", nome:"Rosenparklaurensberg"});
                    DB.create({cod:14, localidade:"Itaguaí", nome:"All Seasons Aachen City"});
                    DB.create({cod:15, localidade:"Itaipava", nome:"Best Western Residenz Harzhohe"});
                    DB.create({cod:16, localidade:"Resende", nome:"Harzer Land Hotel"});
                    DB.create({cod:17, localidade:"Niteroi", nome:"Aquis Grana Cityhotel"});
                    DB.create({cod:18, localidade:"Itatiaia", nome:"Mercure Hotel Aachen Europaplatz"});
                    DB.create({cod:19, localidade:"Araruama", nome:"Pullman Aachen Quellenhof"});
                    DB.create({cod:20, localidade:"Niteroi", nome:"Mimosa Palace"});
                    DB.create({cod:21, localidade:"Nova Iguacu", nome:"Majestic"});
                    DB.create({cod:22, localidade:"Sao Pedro Da Aldeia", nome:"Seybouse"});
                    DB.create({cod:23, localidade:"Quissama", nome:"First Hotel Europa"});
                    DB.create({cod:24, localidade:"Nova Iguacu", nome:"Hilton Al Ain Hotel"});
                    DB.create({cod:25, localidade:"Penedo", nome:"City Seasons Al Ain"});
                    DB.create({cod:26, localidade:"Ilha Grande", nome:"Danat Al Ain Resort Exintercon"});
                    DB.create({cod:27, localidade:"Rio De Janeiro", nome:"Mercure Grand Jebel Hafeet"});
                    DB.create({cod:28, localidade:"Volta Redonda", nome:"Al Ain Rotana Hotel"});
                    DB.create({cod:29, localidade:"Arraial Do Cabo", nome:"Scandic Aarhus Hotel"});
                    DB.create({cod:30, localidade:"Rio Das Ostras", nome:"Radisson Blu Scandinavia Hotel Aarhus"});
                    DB.create({cod:31, localidade:"Quissama", nome:"Plaza Inn Flat Araxa"});
                    DB.create({cod:32, localidade:"Itatiaia", nome:"Hotel Banyan"});
                    DB.create({cod:33, localidade:"Miguel Pereira", nome:"Sport Vital Central Swiss Quality Hotel"});
                    DB.create({cod:34, localidade:"Itatiaia", nome:"Hotel Elisabethpark"});
                    DB.create({cod:35, localidade:"Saquarema", nome:"Weismayr"});
                    DB.create({cod:36, localidade:"Niteroi", nome:"Impuls Tirol Hotel"});
                    DB.create({cod:37, localidade:"Nova Friburgo", nome:"Latini Hotel"});
                    DB.create({cod:38, localidade:"Ilha Grande", nome:"Karwendelhof"});
                    DB.create({cod:39, localidade:"Itaperuna", nome:"Kertess"});
                    DB.create({cod:40, localidade:"Saquarema", nome:"Schlosshotel Rosenegg"});
                    DB.create({cod:41, localidade:"Itaipava", nome:"Grand Hotel Zell Am See Wellness Deluxe Half Board"});
                    DB.create({cod:42, localidade:"Marica", nome:"Alpenhotel Kindl"});
                    DB.create({cod:43, localidade:"Jabaquara", nome:"Boutique Hotel Steinerwirt 1493"});
                    DB.create({cod:44, localidade:"Itatiaia", nome:"Hotel Austria Bellevue"});
                    DB.create({cod:45, localidade:"Rio De Janeiro", nome:"Hotel Goldener Greif"});
                    DB.create({cod:46, localidade:"Barra Mansa", nome:"Austria Trend Alpine Resort Fieberbrunn"});
                    DB.create({cod:47, localidade:"Macae", nome:"Hotel Schloss Lebenberg"});
                    DB.create({cod:48, localidade:"Itaperuna", nome:"Antonius"});
                    DB.create({cod:49, localidade:"Petropolis", nome:"Toni"});
                    DB.create({cod:50, localidade:"Ilha Grande", nome:"Hotel Eva Village"});
                    DB.create({cod:51, localidade:"Paraty", nome:"Panther Hotel"});
                    DB.create({cod:52, localidade:"Marica", nome:"Hotel Alpenbad Hohenhaus"});
                    DB.create({cod:53, localidade:"Nilopolis", nome:"Interalpenhotel Tyrol"});
                    DB.create({cod:54, localidade:"Nilopolis", nome:"Hotel Fliana"});
                    DB.create({cod:55, localidade:"Paraty", nome:"Kempinski Hotel Das Tirol"});
                    DB.create({cod:56, localidade:"Angra Dos Reis", nome:"Hotel Badhaus"});
                    DB.create({cod:57, localidade:"Ilha Grande", nome:"Lebzelter"});
                    DB.create({cod:58, localidade:"Nova Iguacu", nome:"Pension Hochwimmer"});
                    DB.create({cod:59, localidade:"Vassouras", nome:"Schonblick"});
                    DB.create({cod:60, localidade:"Barra Do Pirai", nome:"Solstein"});
                    DB.create({cod:61, localidade:"Paraty", nome:"Ferienhotel Kaltschmid"});
                    DB.create({cod:62, localidade:"Araruama", nome:"Am Romerweg"});
                    DB.create({cod:63, localidade:"Búzios", nome:"Hotel Aktiv Sparesort Alpenpark"});
                    DB.create({cod:64, localidade:"Barra Mansa", nome:"Mavida"});
                    DB.create({cod:65, localidade:"Teresopolis", nome:"Schloss Pichlarn Spa Golf Resort"});
                    DB.create({cod:66, localidade:"Duque De Caxias", nome:"Eckartauerhof"});
                    DB.create({cod:67, localidade:"Itaperuna", nome:"Hotel Elisabeth"});
                    DB.create({cod:68, localidade:"Macae", nome:"Rainhof"});
                    DB.create({cod:69, localidade:"Campos Dos Goytacazes", nome:"Tiefenbrunner Hotel"});
                    DB.create({cod:70, localidade:"Cabo Frio", nome:"Alpenhotel Oetz"});
                    DB.create({cod:71, localidade:"Nilopolis", nome:"Kirchberger Hof"});
                    DB.create({cod:72, localidade:"Jacarepagua", nome:"Cmb"});
                    DB.create({cod:73, localidade:"Trindade", nome:"Hotel Habicher Hof"});
                    DB.create({cod:74, localidade:"Rio Claro", nome:"Hotel Gasthof Mauth Tui"});
                    DB.create({cod:75, localidade:"Galeao", nome:"Park"});
                    DB.create({cod:76, localidade:"Miguel Pereira", nome:"Pension Schonblick"});
                    DB.create({cod:77, localidade:"Campos", nome:"Sonne"});
                    DB.create({cod:78, localidade:"Itaborai", nome:"Tauernhof"});
                    DB.create({cod:79, localidade:"Belford Roxo", nome:"Gasteheim Prantl"});
                    DB.create({cod:80, localidade:"Nova Friburgo", nome:"Hotel Erhart"});
                    DB.create({cod:81, localidade:"Ilha Grande", nome:"Wellnesshotel Schonruh"});
                    DB.create({cod:82, localidade:"Nova Iguacu", nome:"Alpenhof Hotel"});
                    DB.create({cod:83, localidade:"Itaborai", nome:"Hotel Arlberg"});
                    DB.create({cod:84, localidade:"Quissama", nome:"Hotel Felsenhof"});
                    DB.create({cod:85, localidade:"Itaguaí", nome:"Tannbergerhof Hotel"});
                    DB.create({cod:86, localidade:"Jabaquara", nome:"Lech Chesa Rosa"});
                    DB.create({cod:87, localidade:"Angra Dos Reis", nome:"Menthof Hotel"});
                    DB.create({cod:88, localidade:"Mangaratiba", nome:"Sonnenhotel Sturbanerhof"});
                    DB.create({cod:89, localidade:"Rio Claro", nome:"Tirolerhof"});
                    DB.create({cod:90, localidade:"Quissama", nome:"Mittagskogel Hotel"});
                    DB.create({cod:91, localidade:"Belford Roxo", nome:"Hotel Gisela"});
                    DB.create({cod:92, localidade:"Nova Friburgo", nome:"Strandhotel Entner"});
                    DB.create({cod:93, localidade:"Itatiaia", nome:"Kleon Hotel"});
                    DB.create({cod:94, localidade:"Rio Das Ostras", nome:"Hotel Hindenburg"});
                    DB.create({cod:95, localidade:"Nova Friburgo", nome:"Alpenhotel Saalbach Hotel"});
                    DB.create({cod:96, localidade:"Volta Redonda", nome:"Gasthof Pension Bergheimat"});
                    DB.create({cod:97, localidade:"Nilopolis", nome:"Familienhotel Vent"});
                    DB.create({cod:98, localidade:"Itaguaí", nome:"Aqi Hotel Schladming"});
                    DB.create({cod:99, localidade:"Angra Dos Reis", nome:"Post"});
                    DB.create({cod:100, localidade:"Paraty", nome:"Hotel Austria"});
                    DB.create({cod:101, localidade:"Angra Dos Reis", nome:"Bergers Sporthotel"});
                    DB.create({cod:102, localidade:"Campos", nome:"Sonngastein"});
                    DB.create({cod:103, localidade:"Barra Do Pirai", nome:"Kur Sporthotel Palace"});
                    DB.create({cod:104, localidade:"Barra Do Pirai", nome:"Sunny"});
                    DB.create({cod:105, localidade:"Jacarepagua", nome:"Oberforsthof"});
                    DB.create({cod:106, localidade:"Sao Pedro Da Aldeia", nome:"Alpinasolden"});
                    DB.create({cod:107, localidade:"Macae", nome:"Sonnenresort Ossiacher See"});
                    DB.create({cod:108, localidade:"Petropolis", nome:"Hotel Alpenkrone"});
                    DB.create({cod:109, localidade:"Santa Teresa", nome:"Hotel Dunza"});
                    DB.create({cod:110, localidade:"Nova Iguacu", nome:"Almferienclub Silbertal"});
                    DB.create({cod:111, localidade:"São Gonçalo", nome:"Gasthof Weisskugel"});
                    DB.create({cod:112, localidade:"Araruama", nome:"Hotel Bruggerhof"});
                    DB.create({cod:113, localidade:"Itaborai", nome:"Harmonyhotel Harfenwirt"});
                    DB.create({cod:114, localidade:"Itatiaia", nome:"Kurund Sporthotel Alpenblick"});
                    DB.create({cod:115, localidade:"Duque De Caxias", nome:"Gartenhotel Daxer"});
                    DB.create({cod:116, localidade:"Belford Roxo", nome:"Lifthotel"});
                    DB.create({cod:117, localidade:"Nilopolis", nome:"Kristall"});
                    DB.create({cod:118, localidade:"Saquarema", nome:"Hotel Gasthof Zur Muhle"});
                    DB.create({cod:119, localidade:"Macae", nome:"Landhotel Vordergrub"});
                    DB.create({cod:120, localidade:"Vassouras", nome:"Sportpension Trauner"});
                    DB.create({cod:121, localidade:"Niteroi", nome:"Hotel Simmerlwirt"});
                    DB.create({cod:122, localidade:"Campos", nome:"Nationalparkhotel Klockerhaus"});
                    DB.create({cod:123, localidade:"Miguel Pereira", nome:"Wiesenhof"});
                    DB.create({cod:124, localidade:"Arraial Do Cabo", nome:"Liebe Sonne"});
                    DB.create({cod:125, localidade:"Rio De Janeiro", nome:"Astrid"});
                    DB.create({cod:126, localidade:"Volta Redonda", nome:"Alpenhof"});
                    DB.create({cod:127, localidade:"Paraty", nome:"Katschberghof"});
                    DB.create({cod:128, localidade:"Nilopolis", nome:"Romerhof"});
                    DB.create({cod:129, localidade:"Vassouras", nome:"Larchenhof"});
                    DB.create({cod:130, localidade:"Quissama", nome:"Sporthotel Molltal"});
                    DB.create({cod:131, localidade:"Paraty", nome:"Garni Oblasser"});
                    DB.create({cod:132, localidade:"Galeao", nome:"Hagleitner Family Balance Hotel Spa"});
                    DB.create({cod:133, localidade:"Itatiaia", nome:"Kirchenwirt"});
                    DB.create({cod:134, localidade:"Cabo Frio", nome:"Hotel Gasthof Post"});
                    DB.create({cod:135, localidade:"Macae", nome:"Tophotel Mein Almhof"});
                    DB.create({cod:136, localidade:"Nilopolis", nome:"Hotel Stefanihof"});
                    DB.create({cod:137, localidade:"Itaperuna", nome:"Schwarzer Adler Hotel"});
                    DB.create({cod:138, localidade:"Resende", nome:"Landgut Zapfenhof"});
                    DB.create({cod:139, localidade:"Sao Pedro Da Aldeia", nome:"Krimmlerfalle Hotel"});
                    DB.create({cod:140, localidade:"Cabo Frio", nome:"Norica Hotel"});
                    DB.create({cod:141, localidade:"Rio De Janeiro", nome:"Hotel Fluchthorn"});
                    DB.create({cod:142, localidade:"Resende", nome:"Stpeter De Luxe"});
                    DB.create({cod:143, localidade:"Miguel Pereira", nome:"Piz Hotel"});
                    DB.create({cod:144, localidade:"Niteroi", nome:"Klosterbraeu"});
                    DB.create({cod:145, localidade:"Duque De Caxias", nome:"Vital Landhotel Schermer"});
                    DB.create({cod:146, localidade:"Itaperuna", nome:"Harisch Weisses Rossl"});
                    DB.create({cod:147, localidade:"Nilopolis", nome:"Kirchplatz"});
                    DB.create({cod:148, localidade:"Cabo Frio", nome:"Karl Schranz"});
                    DB.create({cod:149, localidade:"Teresopolis", nome:"Tyrol"});
                    DB.create({cod:150, localidade:"Niteroi", nome:"Hotel Fahrner"});
                    DB.create({cod:151, localidade:"Miguel Pereira", nome:"Hotel Florl"});
                    DB.create({cod:152, localidade:"Duque De Caxias", nome:"Hotel Bergheim"});
                    DB.create({cod:153, localidade:"Angra Dos Reis", nome:"Hotel Barenhof"});
                    DB.create({cod:154, localidade:"São Gonçalo", nome:"Der Waldhof"});
                    DB.create({cod:155, localidade:"Volta Redonda", nome:"Hotel Astoria"});
                    DB.create({cod:156, localidade:"Niteroi", nome:"Jaegerwirt"});
                    DB.create({cod:157, localidade:"Itatiaia", nome:"Maria Theresia"});
                    DB.create({cod:158, localidade:"Volta Redonda", nome:"Tirolerhof"});
                    DB.create({cod:159, localidade:"Angra Dos Reis", nome:"Strasshofer"});
                    DB.create({cod:160, localidade:"Itaipava", nome:"Zillertalerhof"});
                    DB.create({cod:161, localidade:"Volta Redonda", nome:"Hotel Alpendomizil Neuhaus"});
                    DB.create({cod:162, localidade:"Itaguaí", nome:"Rauchenwalderhof"});
                    DB.create({cod:163, localidade:"Jabaquara", nome:"Hotel Alpina"});
                    DB.create({cod:164, localidade:"Santa Teresa", nome:"Hotel Cristallago"});
                    DB.create({cod:165, localidade:"Teresopolis", nome:"Stefanie Hotel"});
                    DB.create({cod:166, localidade:"Sao Pedro Da Aldeia", nome:"Hampton Inn Suites Edmontonwest"});
                    DB.create({cod:167, localidade:"Trindade", nome:"Best Western Plus Westwood Inn"});
                    DB.create({cod:168, localidade:"Niteroi", nome:"Best Western Plus Denham Inn Suites"});
                    DB.create({cod:169, localidade:"Galeao", nome:"Travelodge Edmonton West Hotel"});
                    DB.create({cod:170, localidade:"Nova Friburgo", nome:"Best Western Plus South Edmonton Inn Suites"});
                    DB.create({cod:171, localidade:"Itaborai", nome:"Travelodge Edmonton South"});
                    DB.create({cod:172, localidade:"São Gonçalo", nome:"Delta Edmonton South"});
                    DB.create({cod:173, localidade:"Miguel Pereira", nome:"Quality Inn Edmonton Intl Airport"});
                    DB.create({cod:174, localidade:"Nova Iguacu", nome:"Courtyard By Marriott Edmonton"});
                    DB.create({cod:175, localidade:"Miguel Pereira", nome:"Comfort Inn Absecon"});
                    DB.create({cod:176, localidade:"Campos", nome:"Best Western Garden State Inn"});
                    DB.create({cod:177, localidade:"Búzios", nome:"Hotel Cavaliere"});
                    DB.create({cod:178, localidade:"Rio Das Ostras", nome:"Ramapendula Hotel"});
                    DB.create({cod:179, localidade:"Araruama", nome:"Hotel Astoria"});
                    DB.create({cod:180, localidade:"Marica", nome:"Gran Hotel"});
                    DB.create({cod:181, localidade:"Arraial Do Cabo", nome:"Hotel Casa Lorenzo"});
                    DB.create({cod:182, localidade:"São Gonçalo", nome:"Sidorme Albacete"});
                    DB.create({cod:183, localidade:"Belford Roxo", nome:"Hotel Castilla"});
                    DB.create({cod:184, localidade:"Miguel Pereira", nome:"Hotel Altozano"});
                    DB.create({cod:185, localidade:"Nova Friburgo", nome:"Nh Albar"});
                    DB.create({cod:186, localidade:"Vassouras", nome:"Parador De Albacete"});
                    DB.create({cod:187, localidade:"Penedo", nome:"Marquesado De Almansa"});
                    DB.create({cod:188, localidade:"Campos", nome:"Hampton Inn Abilene"});
                    DB.create({cod:189, localidade:"Angra Dos Reis", nome:"Sleep Inn Suites Abilene"});
                    DB.create({cod:190, localidade:"Jacarepagua", nome:"Hampton Inn Sweetwater Tx"});
                    DB.create({cod:191, localidade:"Itaperuna", nome:"Hampton Inn Brownwood"});
                    DB.create({cod:192, localidade:"São Gonçalo", nome:"Best Western Abilene Inn Suites"});
                    DB.create({cod:193, localidade:"São Pedro Da Serra", nome:"Ibis Marcory"});
                    DB.create({cod:194, localidade:"Itaguaí", nome:"Pullman Abidjan"});
                    DB.create({cod:195, localidade:"Itaguaí", nome:"Albuquerquedays Inn West"});
                    DB.create({cod:196, localidade:"Itaperuna", nome:"Econo Lodge"});
                    DB.create({cod:197, localidade:"Vassouras", nome:"Comfort Inn Suites North"});
                    DB.create({cod:198, localidade:"Macae", nome:"Motel 6 Albuquerque South Airport"});
                    DB.create({cod:199, localidade:"Galeao", nome:"La Quinta Inn Albuquerque Airport"});
                    DB.create({cod:200, localidade:"Duque De Caxias", nome:"Comfort Inn"});
                    DB.create({cod:201, localidade:"Araruama", nome:"Hilton Garden Inn Albuq Nrio Rancho"});
                    DB.create({cod:202, localidade:"Volta Redonda", nome:"Hampton Inn Albuquerqueairport"});
                    DB.create({cod:203, localidade:"Paraty", nome:"Homewood Suites By Hilton Albuquerque Uptown"});
                    DB.create({cod:204, localidade:"Quissama", nome:"Hampton Inn Suites Albuquerquecoors Road"});
                    DB.create({cod:205, localidade:"Jabaquara", nome:"Embassy Suites Albuquerque Hot"});
                    DB.create({cod:206, localidade:"Volta Redonda", nome:"Best Western Plus Rio Grande Inn"});
                    DB.create({cod:207, localidade:"Paraty", nome:"Rodeway Inn Midtown"});
                    DB.create({cod:208, localidade:"Paraty", nome:"Ramada Albuquerque Airport"});
                    DB.create({cod:209, localidade:"Itaguaí", nome:"Comfort Inn West"});
                    DB.create({cod:210, localidade:"Nova Friburgo", nome:"Sleep Inn Airport"});
                    DB.create({cod:211, localidade:"Itaperuna", nome:"Red Roof Inn Suites Albuquerque"});
                    DB.create({cod:212, localidade:"São Gonçalo", nome:"Hotel Duca Degli Abruzzi"});
                    DB.create({cod:213, localidade:"São Pedro Da Serra", nome:"Breaking Business Hotel"});
                    DB.create({cod:214, localidade:"Barra Mansa", nome:"Best Western Parco Paglia Hotel"});
                    DB.create({cod:215, localidade:"Macae", nome:"Dinas Hotel"});
                    DB.create({cod:216, localidade:"Mangaratiba", nome:"Protea Hotel Asokoro"});
                    DB.create({cod:217, localidade:"Parati", nome:"Hilton Garden Inn Albany Hotel"});
                    DB.create({cod:218, localidade:"Duque De Caxias", nome:"Hampton Inn Albany At Albany Mall"});
                    DB.create({cod:219, localidade:"Itatiaia", nome:"Best Western Albany Mall Inn Suites"});
                    DB.create({cod:220, localidade:"Ilha Grande", nome:"Quality Inn Merry Acres"});
                    DB.create({cod:221, localidade:"Resende", nome:"Sleep Inn"});
                    DB.create({cod:222, localidade:"Búzios", nome:"Meldrum House Hotel"});
                    DB.create({cod:223, localidade:"Campos", nome:"Aberdeen Youth"});
                    DB.create({cod:224, localidade:"Arraial Do Cabo", nome:"Mercure Ardoe House Hotel Spa"});
                    DB.create({cod:225, localidade:"Santa Teresa", nome:"Loch Kinord Hotel"});
                    DB.create({cod:226, localidade:"Ilha Grande", nome:"Norwood Hall Hotel"});
                    DB.create({cod:227, localidade:"Resende", nome:"Swallow Thainstone House Hotel"});
                    DB.create({cod:228, localidade:"Arraial Do Cabo", nome:"Thistle Aberdeen Airport Hotel"});
                    DB.create({cod:229, localidade:"São Gonçalo", nome:"Holiday Inn Express Aberdeen City Centre"});
                    DB.create({cod:230, localidade:"Saquarema", nome:"Doubletree By Hilton Aberdeen City Centre"});
                    DB.create({cod:231, localidade:"Nova Iguacu", nome:"Kilmarnock Arms Hotel"});
                    DB.create({cod:232, localidade:"Cabo Frio", nome:"Hotel Aberdeen Douglas"});
                    DB.create({cod:233, localidade:"Saquarema", nome:"Hilton Aberdeen Treetops Hotel"});
                    DB.create({cod:234, localidade:"Nova Friburgo", nome:"Banff Springs Hotel"});
                    DB.create({cod:235, localidade:"Araruama", nome:"Huntly Arms Hotel"});
                    DB.create({cod:236, localidade:"Santa Teresa", nome:"Station Hotel Aberdeen"});
                    DB.create({cod:237, localidade:"Paraty", nome:"Holiday Inn Aberdeenwest"});
                    DB.create({cod:238, localidade:"Itaperuna", nome:"Thistle Aberdeen Altens Hotel"});
                    DB.create({cod:239, localidade:"Petropolis", nome:"Hotel Aberdeen Marriott"});
                    DB.create({cod:240, localidade:"Teresopolis", nome:"Carmelite Hotel"});
                    DB.create({cod:241, localidade:"Itaborai", nome:"Quality Suites Spa"});
                    DB.create({cod:242, localidade:"São Pedro Da Serra", nome:"Residhome Arcachon Plazza"});
                    DB.create({cod:243, localidade:"São Pedro Da Serra", nome:"Maeva Le Trianon"});
                    DB.create({cod:244, localidade:"Itaipava", nome:"Maeva La Jetee Des Marins"});
                    DB.create({cod:245, localidade:"Nova Iguacu", nome:"Novotel Arcachon"});
                    DB.create({cod:246, localidade:"Itatiaia", nome:"Ocean Breeze Acapulco"});
                    DB.create({cod:247, localidade:"Rio Das Ostras", nome:"Hotel Encanto"});
                    DB.create({cod:248, localidade:"Vassouras", nome:"One Acapulco Costera"});
                    DB.create({cod:249, localidade:"São Gonçalo", nome:"Hotel Boutique Casa Yalma Kaan"});
                    DB.create({cod:250, localidade:"Petropolis", nome:"Holiday Inn Resort Acapulco"});
                    DB.create({cod:251, localidade:"Búzios", nome:"Hotel Baxar"});
                    DB.create({cod:252, localidade:"Santa Teresa", nome:"Crowne Plaza Hotel Acapulco"});
                    DB.create({cod:253, localidade:"Santa Teresa", nome:"Park Royal Acapulco All Inclusive"});
                    DB.create({cod:254, localidade:"Itaipava", nome:"Alba Suites Acapulco"});
                    DB.create({cod:255, localidade:"Jabaquara", nome:"Auto Hotel Ritz"});
                    DB.create({cod:256, localidade:"Resende", nome:"Romano Palace Hotel"});
                    DB.create({cod:257, localidade:"Itaperuna", nome:"Tortuga Acapulco"});
                    DB.create({cod:258, localidade:"Barra Do Pirai", nome:"Playa Suites Acapulco"});
                    DB.create({cod:259, localidade:"Barra Do Pirai", nome:"El Hotelito"});
                    DB.create({cod:260, localidade:"Duque De Caxias", nome:"Acapulco Malibu Hotel"});
                    DB.create({cod:261, localidade:"Belford Roxo", nome:"Hotel Calinda Beach Acapulco"});
                    DB.create({cod:262, localidade:"Parati", nome:"The Fairmont Pierre Marques"});
                    DB.create({cod:263, localidade:"Parati", nome:"Acasol Hotel"});
                    DB.create({cod:264, localidade:"Campos Dos Goytacazes", nome:"Las Torres Gemelas Private Suites"});
                    DB.create({cod:265, localidade:"Rio Claro", nome:"Riviera Park"});
                    DB.create({cod:266, localidade:"Arraial Do Cabo", nome:"Agua Marina"});
                    DB.create({cod:267, localidade:"Marica", nome:"Cay Beach Papagayo"});
                    DB.create({cod:268, localidade:"Quissama", nome:"Villas Mammamia"});
                    DB.create({cod:269, localidade:"Marica", nome:"Isabel Apartamentos Incl Rent A Car"});
                    DB.create({cod:270, localidade:"Rio Das Ostras", nome:"Finca La Crucita Incl Rent A Car"});
                    DB.create({cod:271, localidade:"Macae", nome:"Fayna"});
                    DB.create({cod:272, localidade:"Itaipava", nome:"Tabaiba Center Apartamentos"});
                    DB.create({cod:273, localidade:"Cabo Frio", nome:"Sol Lanzarote Residente Canario"});
                    DB.create({cod:274, localidade:"Santa Teresa", nome:"Los Tulipanes Apartamentos"});
                    DB.create({cod:275, localidade:"Santa Teresa", nome:"Paradise Island"});
                    DB.create({cod:276, localidade:"Itatiaia", nome:"San Marcial Apartamentos Incl Rent A Car"});
                    DB.create({cod:277, localidade:"Petropolis", nome:"H10 Bahia Blanca Rock"});
                    DB.create({cod:278, localidade:"Itaborai", nome:"Hotel Blue Sea Corbeta"});
                    DB.create({cod:279, localidade:"Búzios", nome:"Las Cascadas Apartments"});
                    DB.create({cod:280, localidade:"Belford Roxo", nome:"Hotel Riu Olivina Resort All Inclusive"});
                    DB.create({cod:281, localidade:"Campos", nome:"Sun Park Aparthotel"});
                    DB.create({cod:282, localidade:"Rio Das Ostras", nome:"H10 Lanzarote Princess Hotel"});
                    DB.create({cod:283, localidade:"Nova Friburgo", nome:"Playa Pocillos Apartamentos"});
                    DB.create({cod:284, localidade:"Nova Friburgo", nome:"El Guarapo Apartamentos"});
                    DB.create({cod:285, localidade:"Barra Mansa", nome:"Villas La Bocaina"});
                    DB.create({cod:286, localidade:"Volta Redonda", nome:"Vik Club Coral Beach Hotel"});
                    DB.create({cod:287, localidade:"Itatiaia", nome:"Villas Brisa Marina"});
                    DB.create({cod:288, localidade:"Quissama", nome:"Hotel Costa Calero"});
                    DB.create({cod:289, localidade:"Saquarema", nome:"Villa Mango"});
                    DB.create({cod:290, localidade:"São Gonçalo", nome:"Villa Christina"});
                    DB.create({cod:291, localidade:"São Gonçalo", nome:"Casitas Alondra"});
                    DB.create({cod:292, localidade:"Niteroi", nome:"Atlantis Las Lomas Apartamentos"});
                    DB.create({cod:293, localidade:"Barra Do Pirai", nome:"Finca La Florida"});
                    DB.create({cod:294, localidade:"Rio Das Ostras", nome:"Luabay Lanzarote Beach Hotel"});
                    DB.create({cod:295, localidade:"São Gonçalo", nome:"Los Hibiscos Apartamentos"});
                    DB.create({cod:296, localidade:"Mangaratiba", nome:"Guacimeta Apartamentos"});
                    DB.create({cod:297, localidade:"Galeao", nome:"Los Zocos"});
                    DB.create({cod:298, localidade:"Nilopolis", nome:"Santa Rosa Aparthotel"});
                    DB.create({cod:299, localidade:"Barra Mansa", nome:"Villas Salinas Matagorda"});
                    DB.create({cod:300, localidade:"Angra Dos Reis", nome:"Las Colinas"});
                    DB.create({cod:301, localidade:"Campos Dos Goytacazes", nome:"Oceano Apartamentos"});
                    DB.create({cod:302, localidade:"Jabaquara", nome:"Finca La Calerita"});
                    DB.create({cod:303, localidade:"Santa Teresa", nome:"Hd Beach Resort"});
                    DB.create({cod:304, localidade:"Volta Redonda", nome:"Be Live Grand Teguise Playa"});
                    DB.create({cod:305, localidade:"Itaguaí", nome:"Be Live Lanzarote Resort Ex Oasis Lanzarote"});
                    DB.create({cod:306, localidade:"Nova Iguacu", nome:"Las Caletas Village"});
                    DB.create({cod:307, localidade:"Cabo Frio", nome:"Villas Janubio"});
                    DB.create({cod:308, localidade:"Niteroi", nome:"Playa Club"});
                    DB.create({cod:309, localidade:"Rio De Janeiro", nome:"El Dorado"});
                    DB.create({cod:310, localidade:"Rio De Janeiro", nome:"Bungalows Coloradamar"});
                    DB.create({cod:311, localidade:"Itaguaí", nome:"Los Gracioseros"});
                    DB.create({cod:312, localidade:"Itaipava", nome:"Villas Los Colores"});
                    DB.create({cod:313, localidade:"Nova Friburgo", nome:"H10 Rubicon Palace Hotel"});
                    DB.create({cod:314, localidade:"Santa Teresa", nome:"Hl Club Playa Blanca"});
                    DB.create({cod:315, localidade:"Itaguaí", nome:"Apartamentos Acuario Sol"});
                    DB.create({cod:316, localidade:"Araruama", nome:"Casa Del Embajador"});
                    DB.create({cod:317, localidade:"Angra Dos Reis", nome:"Panorama"});
                    DB.create({cod:318, localidade:"Galeao", nome:"Lanzarote Paradise Apartamentos"});
                    DB.create({cod:319, localidade:"Itatiaia", nome:"Sandos Papagayo Beach Resort"});
                    DB.create({cod:320, localidade:"Itaguaí", nome:"Hipotels Natura Palace"});
                    DB.create({cod:321, localidade:"Rio Das Ostras", nome:"Lanzarote Village"});
                    DB.create({cod:322, localidade:"Macae", nome:"Balcon Del Mar Apartamentos"});
                    DB.create({cod:323, localidade:"Quissama", nome:"Iberostar Papagayo"});
                    DB.create({cod:324, localidade:"Cabo Frio", nome:"Hotel Barcelo Lanzarote Resort"});
                    DB.create({cod:325, localidade:"Araruama", nome:"Hipotels La Geria"});
                    DB.create({cod:326, localidade:"Sao Pedro Da Aldeia", nome:"Thb Flora Aparthotel"});
                    DB.create({cod:327, localidade:"Araruama", nome:"Costa Sal"});
                    DB.create({cod:328, localidade:"Ilha Grande", nome:"Rocas Blancas"});
                    DB.create({cod:329, localidade:"Jabaquara", nome:"El Trebol Apartamentos"});
                    DB.create({cod:330, localidade:"São Gonçalo", nome:"Cinco Plazas"});
                    DB.create({cod:331, localidade:"Nova Iguacu", nome:"Iberostar La Bocayna Village"});
                    DB.create({cod:332, localidade:"Teresopolis", nome:"Sands Beach Villas Resort Uk"});
                    DB.create({cod:333, localidade:"Duque De Caxias", nome:"Las Costas"});
                    DB.create({cod:334, localidade:"Nova Iguacu", nome:"Los Pueblos Aptos"});
                    DB.create({cod:335, localidade:"Volta Redonda", nome:"Playamar Apartamentos"});
                    DB.create({cod:336, localidade:"Ilha Grande", nome:"Hotel Royal Monica"});
                    DB.create({cod:337, localidade:"Parati", nome:"Mansion Nazaret Hotel"});
                    DB.create({cod:338, localidade:"Paraty", nome:"Luz Y Mar Apartaments"});
                    DB.create({cod:339, localidade:"Parati", nome:"Celeste Apartamentos"});
                    DB.create({cod:340, localidade:"Nilopolis", nome:"Iberostar Lanzarote Park Aparthotel"});
                    DB.create({cod:341, localidade:"Arraial Do Cabo", nome:"Hotel Hesperia Lanzarote"});
                    DB.create({cod:342, localidade:"Nilopolis", nome:"Sun Grove Villas Spa Incl Rent A Car"});
                    DB.create({cod:343, localidade:"Niteroi", nome:"Villa Alena"});
                    DB.create({cod:344, localidade:"Santa Teresa", nome:"Vistas Salinas"});
                    DB.create({cod:345, localidade:"Rio Claro", nome:"Velazquez"});
                    DB.create({cod:346, localidade:"Niteroi", nome:"Hotel Diamar"});
                    DB.create({cod:347, localidade:"Itaipava", nome:"Los Fariones Hotel"});
                    DB.create({cod:348, localidade:"Penedo", nome:"Apartamentos Aguazul"});
                    DB.create({cod:349, localidade:"Duque De Caxias", nome:"Alondra Suites"});
                    DB.create({cod:350, localidade:"Macae", nome:"San Francisco Park"});
                    DB.create({cod:351, localidade:"Vassouras", nome:"Hyde Park Lane Villas"});
                    DB.create({cod:352, localidade:"Jabaquara", nome:"Plaza Azul Apartamentos"});
                    DB.create({cod:353, localidade:"Ilha Grande", nome:"Plaza Palmeras Apartamentos"});
                    DB.create({cod:354, localidade:"Arraial Do Cabo", nome:"Los Ficus Aparthotel"});
                    DB.create({cod:355, localidade:"Itaborai", nome:"Miramar Hotel"});
                    DB.create({cod:356, localidade:"Ilha Grande", nome:"Guinate"});
                    DB.create({cod:357, localidade:"Nova Friburgo", nome:"Hipotels Natura Garden Apartamentos"});
                    DB.create({cod:358, localidade:"Macae", nome:"Molino De Guatiza"});
                    DB.create({cod:359, localidade:"Rio De Janeiro", nome:"Casa De Hilario"});
                    DB.create({cod:360, localidade:"Galeao", nome:"Sun Royal Aparthotel"});
                    DB.create({cod:361, localidade:"Marica", nome:"Parque Tropical"});
                    DB.create({cod:362, localidade:"Angra Dos Reis", nome:"Rosamar"});
                    DB.create({cod:363, localidade:"Mangaratiba", nome:"Hotel Barcelo La Galea"});
                    DB.create({cod:364, localidade:"Rio Das Ostras", nome:"Aloe"});
                    DB.create({cod:365, localidade:"Barra Do Pirai", nome:"Villas El Varadero"});
                    DB.create({cod:366, localidade:"Arraial Do Cabo", nome:"Corona Mar Apartamentos"});
                    DB.create({cod:367, localidade:"Campos Dos Goytacazes", nome:"Teneguia"});
                    DB.create({cod:368, localidade:"São Gonçalo", nome:"Casas Del Sol"});
                    DB.create({cod:369, localidade:"Itatiaia", nome:"Clarion Inn Suites Atlantic City North"});
                    DB.create({cod:370, localidade:"Búzios", nome:"Comfort Inn Suites"});
                    DB.create({cod:371, localidade:"Santa Teresa", nome:"Harrahs Atlantic City"});
                    DB.create({cod:372, localidade:"Jacarepagua", nome:"Showboat Atlantic City"});
                    DB.create({cod:373, localidade:"Nova Friburgo", nome:"Ballys Park Place"});
                    DB.create({cod:374, localidade:"Rio De Janeiro", nome:"Best Western Envoy Inn"});
                    DB.create({cod:375, localidade:"Nova Iguacu", nome:"Best Western Plus Atlantic City West Extended Stay Suites"});
                    DB.create({cod:376, localidade:"Marica", nome:"Quality Hotel Bayside Resort"});
                    DB.create({cod:377, localidade:"Mangaratiba", nome:"Comfort Inn North"});
                    DB.create({cod:378, localidade:"Petropolis", nome:"Clarion Hotel Convention Center Atlantic City West"});
                    DB.create({cod:379, localidade:"Rio Das Ostras", nome:"Akkoc Butik Hotel"});
                    DB.create({cod:380, localidade:"São Pedro Da Serra", nome:"Surmeli Adana Hotel"});
                    DB.create({cod:381, localidade:"Itaipava", nome:"Mavi Surmeli"});
                    DB.create({cod:382, localidade:"São Gonçalo", nome:"Riva Resatbey Boutique Busines Hotel"});
                    DB.create({cod:383, localidade:"Macae", nome:"Seyhan"});
                    DB.create({cod:384, localidade:"Itaborai", nome:"Sahin Yuvasi"});
                    DB.create({cod:385, localidade:"Nova Iguacu", nome:"Vera Santa Maria Hotel"});
                    DB.create({cod:386, localidade:"Ilha Grande", nome:"Istankoy Hotel Kusadasi"});
                    DB.create({cod:387, localidade:"Campos Dos Goytacazes", nome:"Olivia Family Suites"});
                    DB.create({cod:388, localidade:"Petropolis", nome:"Ekin Hotel"});
                    DB.create({cod:389, localidade:"Jabaquara", nome:"Akbulut Hotel Spa"});
                    DB.create({cod:390, localidade:"Itaguaí", nome:"City Hotel"});
                    DB.create({cod:391, localidade:"Duque De Caxias", nome:"Atlantique Holiday Club"});
                    DB.create({cod:392, localidade:"Marica", nome:"Grand Belish"});
                    DB.create({cod:393, localidade:"Vassouras", nome:"Lavista Boutique Hotel Spa"});
                    DB.create({cod:394, localidade:"Itaipava", nome:"Altinbas Apart Hotel"});
                    DB.create({cod:395, localidade:"Nova Iguacu", nome:"Hotel Ogerim"});
                    DB.create({cod:396, localidade:"Vassouras", nome:"Talat Hotel"});
                    DB.create({cod:397, localidade:"Quissama", nome:"Cidihan Hotel"});
                    DB.create({cod:398, localidade:"Resende", nome:"Palm Hotel"});
                    DB.create({cod:399, localidade:"Arraial Do Cabo", nome:"Club Prestige Hotel"});
                    DB.create({cod:400, localidade:"Duque De Caxias", nome:"Moya Pasha Apart"});
                    DB.create({cod:401, localidade:"Rio De Janeiro", nome:"Ephesus Boutique Hotel"});
                    DB.create({cod:402, localidade:"Campos Dos Goytacazes", nome:"Mor Suite Hotel"});
                    DB.create({cod:403, localidade:"Búzios", nome:"Palmin Hotel"});
                    DB.create({cod:404, localidade:"Duque De Caxias", nome:"Alibabam Hotel Apartment"});
                    DB.create({cod:405, localidade:"Itatiaia", nome:"Cande Onura Hotel"});
                    DB.create({cod:406, localidade:"Penedo", nome:"Akdas Kusadasi"});
                    DB.create({cod:407, localidade:"Quissama", nome:"Pine Bay Holiday Resort"});
                    DB.create({cod:408, localidade:"Campos", nome:"Coastlight Hotel"});
                    DB.create({cod:409, localidade:"Vassouras", nome:"Adakule"});
                    DB.create({cod:410, localidade:"Nova Iguacu", nome:"Richmond Ephesus Resort Half Board"});
                    DB.create({cod:411, localidade:"Miguel Pereira", nome:"Imbat Hotel"});
                    DB.create({cod:412, localidade:"São Gonçalo", nome:"Club Mersin Beach Promo"});
                    DB.create({cod:413, localidade:"Campos Dos Goytacazes", nome:"Ephesia Holiday Beach Club"});
                    DB.create({cod:414, localidade:"Campos Dos Goytacazes", nome:"Atli Hotel"});
                    DB.create({cod:415, localidade:"Rio Claro", nome:"Efe Boutique Hotel"});
                    DB.create({cod:416, localidade:"Itaipava", nome:"Cande Festival Hotel Kullaniilmiyor"});
                    DB.create({cod:417, localidade:"Itaperuna", nome:"Grand Blue Sky International"});
                    DB.create({cod:418, localidade:"Penedo", nome:"Grand Kurdoglu Hotel"});
                    DB.create({cod:419, localidade:"Galeao", nome:"Rosy Pension"});
                    DB.create({cod:420, localidade:"Itaipava", nome:"Golden Gate"});
                    DB.create({cod:421, localidade:"Teresopolis", nome:"Happy Apart Hotel"});
                    DB.create({cod:422, localidade:"Barra Do Pirai", nome:"Tuntas Apartments Kusadasi"});
                    DB.create({cod:423, localidade:"Itaborai", nome:"Club Hotel Ephesus Princess"});
                    DB.create({cod:424, localidade:"Itaborai", nome:"Alp Hotel"});
                    DB.create({cod:425, localidade:"Trindade", nome:"Asena"});
                    DB.create({cod:426, localidade:"Itaperuna", nome:"Hotel Derici"});
                    DB.create({cod:427, localidade:"Cabo Frio", nome:"Ida Apart Hotel"});
                    DB.create({cod:428, localidade:"Sao Pedro Da Aldeia", nome:"Akdeniz"});
                    DB.create({cod:429, localidade:"Búzios", nome:"Seaview Suit"});
                    DB.create({cod:430, localidade:"Vassouras", nome:"Atinc Hotel"});
                    DB.create({cod:431, localidade:"Volta Redonda", nome:"Kayhanbey Hotel"});
                    DB.create({cod:432, localidade:"Paraty", nome:"Tatlises Hotel"});
                    DB.create({cod:433, localidade:"Itaperuna", nome:"Surtel Hotel"});
                    DB.create({cod:434, localidade:"Rio Claro", nome:"Charisma Deluxe"});
                    DB.create({cod:435, localidade:"Araruama", nome:"Sealight Resort Hotel"});
                    DB.create({cod:436, localidade:"Nilopolis", nome:"Minay"});
                    DB.create({cod:437, localidade:"Angra Dos Reis", nome:"Korumar Hotel Deluxe"});
                    DB.create({cod:438, localidade:"Itaborai", nome:"Omer Holiday Resort"});
                    DB.create({cod:439, localidade:"Cabo Frio", nome:"Yonca Hotel Apart"});
                    DB.create({cod:440, localidade:"Macae", nome:"Saturn Hotel"});
                    DB.create({cod:441, localidade:"Teresopolis", nome:"Hotel Altinsaray"});
                    DB.create({cod:442, localidade:"Barra Do Pirai", nome:"Comfort Inn Anzac Highway"});
                    DB.create({cod:443, localidade:"Vassouras", nome:"Quality Old Adelaide"});
                    DB.create({cod:444, localidade:"Belford Roxo", nome:"Fire Station Inn"});
                    DB.create({cod:445, localidade:"Rio Das Ostras", nome:"Buxton Manor"});
                    DB.create({cod:446, localidade:"Itaguaí", nome:"Majestic Minima Hotel"});
                    DB.create({cod:447, localidade:"Itaborai", nome:"Mclaren Vale Studio Apartments"});
                    DB.create({cod:448, localidade:"Teresopolis", nome:"Best Western Ensenada Motor Inn"});
                    DB.create({cod:449, localidade:"Campos Dos Goytacazes", nome:"Stamford Grand Adelaide"});
                    DB.create({cod:450, localidade:"Ilha Grande", nome:"Oaks Liberty Towers2 Bedroom"});
                    DB.create({cod:451, localidade:"Macae", nome:"Kleopatra Bebek Hotel"});
                    DB.create({cod:452, localidade:"Nova Friburgo", nome:"Azalea Apart Hotel"});
                    DB.create({cod:453, localidade:"Jabaquara", nome:"Seda Apart Hotel"});
                    DB.create({cod:454, localidade:"Jacarepagua", nome:"Mc Mahberi Beach Hotel"});
                    DB.create({cod:455, localidade:"Mangaratiba", nome:"Mirage Apart Hotel"});
                    DB.create({cod:456, localidade:"Itaborai", nome:"Kleopatra Celine"});
                    DB.create({cod:457, localidade:"Nova Iguacu", nome:"Drita"});
                    DB.create({cod:458, localidade:"Itaborai", nome:"Moonlight Hotel"});
                    DB.create({cod:459, localidade:"Angra Dos Reis", nome:"Kleopatra Royal Palm Hotel"});
                    DB.create({cod:460, localidade:"Macae", nome:"Riviera Hotel"});
                    DB.create({cod:461, localidade:"São Pedro Da Serra", nome:"Selvi"});
                    DB.create({cod:462, localidade:"Niteroi", nome:"Residence Anfora"});
                    DB.create({cod:463, localidade:"Rio De Janeiro", nome:"Orient Suite Hotel"});
                    DB.create({cod:464, localidade:"Penedo", nome:"Maritim Hotel Club Alantur"});
                    DB.create({cod:465, localidade:"Rio Claro", nome:"Cleopatra Sud Princess Apart"});
                    DB.create({cod:466, localidade:"Itaborai", nome:"Mirabell Hotel"});
                    DB.create({cod:467, localidade:"Quissama", nome:"My Home Resort Hotel"});
                    DB.create({cod:468, localidade:"Angra Dos Reis", nome:"Club Aqua Plaza"});
                    DB.create({cod:469, localidade:"Miguel Pereira", nome:"Kleopatra Ada Hotel"});
                    DB.create({cod:470, localidade:"Arraial Do Cabo", nome:"Hotel Antik"});
                    DB.create({cod:471, localidade:"São Pedro Da Serra", nome:"Hotel Club Kastalia"});
                    DB.create({cod:472, localidade:"Ilha Grande", nome:"Seaport Hotel"});
                    DB.create({cod:473, localidade:"São Gonçalo", nome:"Volkan Hotel"});
                    DB.create({cod:474, localidade:"Arraial Do Cabo", nome:"Palmera Kleopatra Beach Hotel"});
                    DB.create({cod:475, localidade:"Nova Iguacu", nome:"Oba Star Hotel"});
                    DB.create({cod:476, localidade:"Sao Pedro Da Aldeia", nome:"Yalihan Hotel"});
                    DB.create({cod:477, localidade:"Penedo", nome:"Titan Select Hotel"});
                    DB.create({cod:478, localidade:"Paraty", nome:"Savk Hotel"});
                    DB.create({cod:479, localidade:"Quissama", nome:"Okan Tower Apart Otel"});
                    DB.create({cod:480, localidade:"Teresopolis", nome:"Almera"});
                    DB.create({cod:481, localidade:"Búzios", nome:"Gold Anez"});
                    DB.create({cod:482, localidade:"Barra Do Pirai", nome:"Telatiye Resort Hotel"});
                    DB.create({cod:483, localidade:"Barra Mansa", nome:"Aska Just In Beach"});
                    DB.create({cod:484, localidade:"Nilopolis", nome:"Sunmaritim Hotel"});
                    DB.create({cod:485, localidade:"Barra Do Pirai", nome:"Sailor Apart Hotel"});
                    DB.create({cod:486, localidade:"Trindade", nome:"Kleopatra South Star"});
                    DB.create({cod:487, localidade:"Macae", nome:"Primera Hotel"});
                    DB.create({cod:488, localidade:"Niteroi", nome:"Ozkaymak Alaaddinn"});
                    DB.create({cod:489, localidade:"Miguel Pereira", nome:"Sentido Gold Island"});
                    DB.create({cod:490, localidade:"Itaipava", nome:"Gorgulu Kleopatra Beach"});
                    DB.create({cod:491, localidade:"Itatiaia", nome:"Sentido Golden Bayex Hotel G"});
                    DB.create({cod:492, localidade:"Jacarepagua", nome:"Sailorson Apart Hotel"});
                    DB.create({cod:493, localidade:"Ilha Grande", nome:"Hotel Panorama"});
                    DB.create({cod:494, localidade:"Nilopolis", nome:"Caprice Apart"});
                    DB.create({cod:495, localidade:"Jacarepagua", nome:"Aramis Hotel"});
                    DB.create({cod:496, localidade:"Mangaratiba", nome:"Club Konakli Hotel"});
                    DB.create({cod:497, localidade:"Nova Iguacu", nome:"Club Paradiso Hotel"});
                    DB.create({cod:498, localidade:"Itaipava", nome:"Grand Okan Hotel"});
                    DB.create({cod:499, localidade:"Quissama", nome:"Grand Zaman Beach Hotel"});
                    DB.create({cod:500, localidade:"Nova Friburgo", nome:"Grand Uysal"});
        
                }
            });
            
        }
    };
    return HotelController;
}

